title: YOUR TITLE
description: YOUR DESCRIPTION
theme: just-the-docs

url: https://aaronbadger.github.io/gh-issues-renderer/

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://aaronbadger.github.io/gh-issues-renderer/
